"""
Create GIF from optimization plot frames.

This script takes the plot frames generated by bayesian_optimize_steering.py
and creates an animated GIF showing the optimization progress.
"""

import argparse
from pathlib import Path
from PIL import Image
import imageio


def create_gif_from_frames(
    frames_dir: Path,
    output_path: Path,
    pattern: str = "optimization_progress_iter_*.png",
    duration: float = 0.5,
    loop: int = 0
):
    """
    Create GIF from frame images.
    
    Args:
        frames_dir: Directory containing frame images
        output_path: Path to save GIF
        pattern: Glob pattern to match frame files
        duration: Duration per frame in seconds
        loop: Number of loops (0 = infinite)
    """
    # Find all frame files
    frame_files = sorted(frames_dir.glob(pattern))
    
    if not frame_files:
        print(f"No frames found matching {pattern} in {frames_dir}")
        return
    
    print(f"Found {len(frame_files)} frames")
    print(f"Creating GIF: {output_path}")
    
    # Load images
    images = []
    for frame_file in frame_files:
        img = Image.open(frame_file)
        images.append(img)
    
    # Create GIF
    imageio.mimsave(
        str(output_path),
        images,
        duration=duration,
        loop=loop
    )
    
    print(f"GIF created: {output_path}")


def parse_args():
    parser = argparse.ArgumentParser(description="Create GIF from optimization frames")
    parser.add_argument(
        "--frames-dir",
        type=Path,
        default=Path("bayesian_opt_results/plots"),
        help="Directory containing frame images"
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=Path("bayesian_opt_results/optimization_animation.gif"),
        help="Path to save GIF"
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="optimization_progress_iter_*.png",
        help="Glob pattern to match frame files"
    )
    parser.add_argument(
        "--duration",
        type=float,
        default=0.5,
        help="Duration per frame in seconds"
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    create_gif_from_frames(
        args.frames_dir,
        args.output_path,
        args.pattern,
        args.duration
    )

